name: "UNet-EfficientNetB7-Dense-BCE"

model:
  architecture: "Unet"
  encoder: "efficientnet-b7"
  encoder_weights: "imagenet"
  activation: "sigmoid"
  in_channels: 3

training:
  learning_rate: 0.0001
  batch_size:
    train: 10
    val: 50
  num_epochs: 100
  device: "cuda"
  num_workers: 0

loss:
  train:
    name: "BCELoss"
    params: {}
  validation:
    name: "BCELoss"
    params: {}

optimizer:
  name: "Adam"
  params:
    lr: 0.0001

metrics:
  - "IoU"

checkpointing:
  save_best: true
  monitor_metric: "val_loss"
  mode: "min"
  save_interval: null
